services:
  #rabbit:
  #  image: rabbitmq:3.13-management
  #  hostname: rabbitmq
  #  ports:
  #    - "5672:5672"
  #    - "15672:15672"
  #  healthcheck:
  #    test: rabbitmq-diagnostics check_port_connectivity
  #    interval: 10s
  #    timeout: 5s
  #    retries: 10
  #    start_period: 5s
  #  extends:
  #    file: common-config.yml
  #    service: network-deploy-service


  accountsdb:
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config


  loansdb:
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config


  cardsdb:
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config



  configserver:
    image: "adjodamawuli/configserver:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    #depends_on:
    #  rabbit:
    #    condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "adjodamawuli/accounts:s7"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    # whenever we are trying to provide an environment variable we need to follow a syntax which is
    # converting all the letters to capital letters and replacing that dot with underscore
    # import: "optional:configserver:http://localhost:8071/" => we copy this from applicaion.yml from one microservices
    # we replace localhost with the configserver service name
    # the prefix will always be configserver
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  loans:
    image: "adjodamawuli/loans:s7"
    container_name: loans-ms
    ports:
      - "8090:8090"

    # whenever we are trying to provide an environment variable we need to follow a syntax which is
    # converting all the letters to capital letters and replacing that dot with underscore
    # import: "optional:configserver:http://localhost:8071/" => we copy this from applicaion.yml from one microservices
    # we replace localhost with the configserver service name
    # the prefix will always be configserver
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "adjodamawuli/cards:s7"
    container_name: cards-ms
    ports:
      - "9000:9000"

    # whenever we are trying to provide an environment variable we need to follow a syntax which is
    # converting all the letters to capital letters and replacing that dot with underscore
    # import: "optional:configserver:http://localhost:8071/" => we copy this from applicaion.yml from one microservices
    # we replace localhost with the configserver service name
    # the prefix will always be configserver
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config


networks:
  eazybank:
    driver: "bridge"