build:
  version: "1.0"


accounts:
  message: "Welcome to EazyBank accounts related prod APIs "
  contactDetails:
    name: "ADJODA Mawuli - Product Owner"
    email: "koffimawuli.adjoda@gmail.com"
  onCallSupport:
    - (33) 786015566
    - (33) 786015566