build:
  version: "3.0"


accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "ADJODA Mawuli - Tech Lead Java"
    email: "koffimawuli.adjoda@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345